/**
 * ISO 3166-2 subdivision code → human-readable name mapping.
 * Covers major countries that appear in analytics.
 * geoip-lite returns region codes like "10" for TH, "CA" for US.
 */

const REGIONS: Record<string, Record<string, string>> = {
  TH: {
    '10': 'กรุงเทพมหานคร', '11': 'สมุทรปราการ', '12': 'นนทบุรี', '13': 'ปทุมธานี',
    '14': 'พระนครศรีอยุธยา', '15': 'อ่างทอง', '16': 'ลพบุรี', '17': 'สิงห์บุรี',
    '18': 'ชัยนาท', '19': 'สระบุรี', '20': 'ชลบุรี', '21': 'ระยอง',
    '22': 'จันทบุรี', '23': 'ตราด', '24': 'ฉะเชิงเทรา', '25': 'ปราจีนบุรี',
    '26': 'นครนายก', '27': 'สระแก้ว', '30': 'นครราชสีมา', '31': 'บุรีรัมย์',
    '32': 'สุรินทร์', '33': 'ศรีสะเกษ', '34': 'อุบลราชธานี', '35': 'ยโสธร',
    '36': 'ชัยภูมิ', '37': 'อำนาจเจริญ', '38': 'บึงกาฬ', '39': 'หนองบัวลำภู',
    '40': 'ขอนแก่น', '41': 'อุดรธานี', '42': 'เลย', '43': 'หนองคาย',
    '44': 'มหาสารคาม', '45': 'ร้อยเอ็ด', '46': 'กาฬสินธุ์', '47': 'สกลนคร',
    '48': 'นครพนม', '49': 'มุกดาหาร', '50': 'เชียงใหม่', '51': 'ลำพูน',
    '52': 'ลำปาง', '53': 'อุตรดิตถ์', '54': 'แพร่', '55': 'น่าน',
    '56': 'พะเยา', '57': 'เชียงราย', '58': 'แม่ฮ่องสอน', '60': 'นครสวรรค์',
    '61': 'อุทัยธานี', '62': 'กำแพงเพชร', '63': 'ตาก', '64': 'สุโขทัย',
    '65': 'พิษณุโลก', '66': 'พิจิตร', '67': 'เพชรบูรณ์', '70': 'ราชบุรี',
    '71': 'กาญจนบุรี', '72': 'สุพรรณบุรี', '73': 'นครปฐม', '74': 'สมุทรสาคร',
    '75': 'สมุทรสงคราม', '76': 'เพชรบุรี', '77': 'ประจวบคีรีขันธ์',
    '80': 'นครศรีธรรมราช', '81': 'กระบี่', '82': 'พังงา', '83': 'ภูเก็ต',
    '84': 'สุราษฎร์ธานี', '85': 'ระนอง', '86': 'ชุมพร', '90': 'สงขลา',
    '91': 'สตูล', '92': 'ตรัง', '93': 'พัทลุง', '94': 'ปัตตานี',
    '95': 'ยะลา', '96': 'นราธิวาส', 'S': 'สมุทรปราการ',
  },
  US: {
    'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas',
    'CA': 'California', 'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware',
    'FL': 'Florida', 'GA': 'Georgia', 'HI': 'Hawaii', 'ID': 'Idaho',
    'IL': 'Illinois', 'IN': 'Indiana', 'IA': 'Iowa', 'KS': 'Kansas',
    'KY': 'Kentucky', 'LA': 'Louisiana', 'ME': 'Maine', 'MD': 'Maryland',
    'MA': 'Massachusetts', 'MI': 'Michigan', 'MN': 'Minnesota', 'MS': 'Mississippi',
    'MO': 'Missouri', 'MT': 'Montana', 'NE': 'Nebraska', 'NV': 'Nevada',
    'NH': 'New Hampshire', 'NJ': 'New Jersey', 'NM': 'New Mexico', 'NY': 'New York',
    'NC': 'North Carolina', 'ND': 'North Dakota', 'OH': 'Ohio', 'OK': 'Oklahoma',
    'OR': 'Oregon', 'PA': 'Pennsylvania', 'RI': 'Rhode Island', 'SC': 'South Carolina',
    'SD': 'South Dakota', 'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah',
    'VT': 'Vermont', 'VA': 'Virginia', 'WA': 'Washington', 'WV': 'West Virginia',
    'WI': 'Wisconsin', 'WY': 'Wyoming', 'DC': 'Washington D.C.',
  },
  JP: {
    '01': 'Hokkaido', '02': 'Aomori', '03': 'Iwate', '04': 'Miyagi',
    '05': 'Akita', '06': 'Yamagata', '07': 'Fukushima', '08': 'Ibaraki',
    '09': 'Tochigi', '10': 'Gunma', '11': 'Saitama', '12': 'Chiba',
    '13': 'Tokyo', '14': 'Kanagawa', '15': 'Niigata', '16': 'Toyama',
    '17': 'Ishikawa', '18': 'Fukui', '19': 'Yamanashi', '20': 'Nagano',
    '21': 'Gifu', '22': 'Shizuoka', '23': 'Aichi', '24': 'Mie',
    '25': 'Shiga', '26': 'Kyoto', '27': 'Osaka', '28': 'Hyogo',
    '29': 'Nara', '30': 'Wakayama', '31': 'Tottori', '32': 'Shimane',
    '33': 'Okayama', '34': 'Hiroshima', '35': 'Yamaguchi', '36': 'Tokushima',
    '37': 'Kagawa', '38': 'Ehime', '39': 'Kochi', '40': 'Fukuoka',
    '41': 'Saga', '42': 'Nagasaki', '43': 'Kumamoto', '44': 'Oita',
    '45': 'Miyazaki', '46': 'Kagoshima', '47': 'Okinawa',
  },
  KR: {
    '11': 'Seoul', '26': 'Busan', '27': 'Daegu', '28': 'Incheon',
    '29': 'Gwangju', '30': 'Daejeon', '31': 'Ulsan', '41': 'Gyeonggi',
    '42': 'Gangwon', '43': 'Chungbuk', '44': 'Chungnam', '45': 'Jeonbuk',
    '46': 'Jeonnam', '47': 'Gyeongbuk', '48': 'Gyeongnam', '49': 'Jeju',
    '50': 'Sejong',
  },
  GB: {
    'ENG': 'England', 'SCT': 'Scotland', 'WLS': 'Wales', 'NIR': 'Northern Ireland',
  },
  DE: {
    'BW': 'Baden-Württemberg', 'BY': 'Bavaria', 'BE': 'Berlin', 'BB': 'Brandenburg',
    'HB': 'Bremen', 'HH': 'Hamburg', 'HE': 'Hesse', 'MV': 'Mecklenburg-Vorpommern',
    'NI': 'Lower Saxony', 'NW': 'North Rhine-Westphalia', 'RP': 'Rhineland-Palatinate',
    'SL': 'Saarland', 'SN': 'Saxony', 'ST': 'Saxony-Anhalt', 'SH': 'Schleswig-Holstein',
    'TH': 'Thuringia',
  },
  SG: { '01': 'Singapore', '02': 'Singapore', '03': 'Singapore', '04': 'Singapore', '05': 'Singapore' },
  VN: {
    '01': 'Lai Châu', '02': 'Lào Cai', '03': 'Hà Giang', '04': 'Cao Bằng',
    '05': 'Sơn La', '06': 'Yên Bái', '07': 'Tuyên Quang', '09': 'Lạng Sơn',
    '13': 'Quảng Ninh', '14': 'Hòa Bình', '15': 'Hà Tây', '18': 'Ninh Bình',
    '20': 'Thái Bình', '21': 'Thanh Hóa', '22': 'Nghệ An', '23': 'Hà Tĩnh',
    '24': 'Quảng Bình', '25': 'Quảng Trị', '26': 'Thừa Thiên-Huế',
    '27': 'Quảng Nam', '28': 'Kon Tum', '29': 'Quảng Ngãi', '30': 'Gia Lai',
    '31': 'Bình Định', '32': 'Phú Yên', '33': 'Đắk Lắk', '34': 'Khánh Hòa',
    '35': 'Lâm Đồng', '36': 'Ninh Thuận', '37': 'Tây Ninh', '38': 'Đồng Nai',
    '39': 'Bình Thuận', '40': 'Long An', '41': 'Bà Rịa-Vũng Tàu',
    '43': 'An Giang', '44': 'Đồng Tháp', '45': 'Tiền Giang', '46': 'Kiên Giang',
    '47': 'Cần Thơ', '48': 'Vĩnh Long', '49': 'Bến Tre', '50': 'Trà Vinh',
    '51': 'Sóc Trăng', '52': 'Bắc Kạn', '53': 'Bắc Giang', '54': 'Bắc Ninh',
    '55': 'Bình Dương', '56': 'Bình Phước', '57': 'Cà Mau', '58': 'Đắk Nông',
    '59': 'Điện Biên', '60': 'Hải Dương', '61': 'Hải Phòng', '62': 'Hà Nam',
    '63': 'Hà Nội', '64': 'Hậu Giang', '65': 'Hồ Chí Minh', '66': 'Hưng Yên',
    '67': 'Nam Định', '68': 'Phú Thọ', '69': 'Thái Nguyên', '70': 'Vĩnh Phúc',
    SG: 'Hồ Chí Minh',
  },
  MY: {
    '01': 'Johor', '02': 'Kedah', '03': 'Kelantan', '04': 'Melaka',
    '05': 'Negeri Sembilan', '06': 'Pahang', '07': 'Penang', '08': 'Perak',
    '09': 'Perlis', '10': 'Selangor', '11': 'Terengganu', '12': 'Sabah',
    '13': 'Sarawak', '14': 'Kuala Lumpur', '15': 'Labuan', '16': 'Putrajaya',
  },
  PH: {
    '01': 'Ilocos', '02': 'Cagayan Valley', '03': 'Central Luzon',
    '05': 'Bicol', '06': 'Western Visayas', '07': 'Central Visayas',
    '08': 'Eastern Visayas', '09': 'Zamboanga Peninsula', '10': 'Northern Mindanao',
    '11': 'Davao', '12': 'SOCCSKSARGEN', '13': 'Caraga', '14': 'BARMM',
    '15': 'Cordillera', '40': 'CALABARZON', '41': 'MIMAROPA', 'NCR': 'Metro Manila',
    'CAR': 'Cordillera', '00': 'Metro Manila',
  },
  ID: {
    'AC': 'Aceh', 'BA': 'Bali', 'BB': 'Bangka Belitung', 'BE': 'Bengkulu',
    'BT': 'Banten', 'GO': 'Gorontalo', 'JA': 'Jambi', 'JB': 'Jawa Barat',
    'JI': 'Jawa Timur', 'JK': 'Jakarta', 'JT': 'Jawa Tengah',
    'KB': 'Kalimantan Barat', 'KI': 'Kalimantan Timur', 'KR': 'Kepulauan Riau',
    'KS': 'Kalimantan Selatan', 'KT': 'Kalimantan Tengah', 'KU': 'Kalimantan Utara',
    'LA': 'Lampung', 'MA': 'Maluku', 'MU': 'Maluku Utara',
    'NB': 'Nusa Tenggara Barat', 'NT': 'Nusa Tenggara Timur',
    'PA': 'Papua', 'PB': 'Papua Barat', 'RI': 'Riau',
    'SA': 'Sulawesi Utara', 'SB': 'Sumatera Barat', 'SG': 'Sulawesi Tenggara',
    'SN': 'Sulawesi Selatan', 'SR': 'Sulawesi Barat', 'SS': 'Sumatera Selatan',
    'ST': 'Sulawesi Tengah', 'SU': 'Sumatera Utara', 'YO': 'Yogyakarta',
  },
  MM: {
    '01': 'Sagaing', '02': 'Bago', '03': 'Magway', '04': 'Mandalay',
    '05': 'Tanintharyi', '06': 'Yangon', '07': 'Ayeyarwady',
    '11': 'Kachin', '12': 'Kayah', '13': 'Kayin', '14': 'Chin',
    '15': 'Mon', '16': 'Rakhine', '17': 'Shan', '18': 'Naypyidaw',
  },
  KH: {
    '01': 'Banteay Meanchey', '02': 'Battambang', '03': 'Kampong Cham',
    '04': 'Kampong Chhnang', '05': 'Kampong Speu', '06': 'Kampong Thom',
    '07': 'Kampot', '08': 'Kandal', '09': 'Koh Kong', '10': 'Kratie',
    '11': 'Mondulkiri', '12': 'Phnom Penh', '13': 'Preah Vihear',
    '14': 'Prey Veng', '15': 'Pursat', '16': 'Ratanakiri',
    '17': 'Siem Reap', '18': 'Sihanoukville', '19': 'Stung Treng',
    '20': 'Svay Rieng', '21': 'Takeo', '22': 'Oddar Meanchey',
    '23': 'Kep', '24': 'Pailin', '25': 'Tboung Khmum',
  },
  LA: {
    'AT': 'Attapeu', 'BK': 'Bokeo', 'BL': 'Bolikhamxai', 'CH': 'Champasak',
    'HO': 'Houaphan', 'KH': 'Khammouan', 'LM': 'Luang Namtha',
    'LP': 'Luang Prabang', 'OU': 'Oudomxay', 'PH': 'Phongsali',
    'SL': 'Salavan', 'SV': 'Savannakhet', 'VI': 'Vientiane Province',
    'VT': 'Vientiane', 'XA': 'Xaignabouli', 'XE': 'Xekong',
    'XI': 'Xiangkhouang', 'XS': 'Xaisomboun',
  },
  BN: {
    'BE': 'Belait', 'BM': 'Brunei-Muara', 'TE': 'Temburong', 'TU': 'Tutong',
  },
}

export function getRegionName(countryCode: string, regionCode: string): string {
  return REGIONS[countryCode]?.[regionCode] ?? regionCode
}
