import { z } from 'zod'
import type { ZodTypeProvider } from 'fastify-type-provider-zod'
import type { FastifyPluginAsync } from 'fastify'
import { prisma } from '../db/client.js'
import { requireAuth, requireRole } from './auth.js'
import { getAccessibleSiteIds } from '../services/siteAccess.js'
import { logActivity } from '../services/activityLog.js'

/**
 * Sites CRUD routes (E6-F1)
 *
 * POST   /api/sites          — register a new site, receive tracking_token
 * GET    /api/sites          — list all active (non-deleted) sites
 * GET    /api/sites/:id      — get single site by UUID
 * DELETE /api/sites/:id      — soft delete (data retained, deleted_at set)
 *
 * The tracking_token is generated by PostgreSQL (gen_random_bytes(32) hex).
 * Site data is retained on soft delete for historical analytics queries.
 */

export const sitesRoute: FastifyPluginAsync = async (fastify) => {
  fastify.addHook('onRequest', requireAuth)
  const app = fastify.withTypeProvider<ZodTypeProvider>()

  const createBodySchema = z.object({
    name: z.string().min(1).max(100),
    domain: z.string().min(1).max(253),
  })

  const idParamsSchema = z.object({ id: z.string().uuid() })

  // ── POST /api/sites ───────────────────────────────────────────────────────

  app.post('/sites', { schema: { body: createBodySchema }, preHandler: [requireRole('admin')] }, async (request, reply) => {
    const { name, domain } = request.body

    // Normalise domain: strip protocol, trailing slashes, www prefix
    const cleanDomain = domain
      .replace(/^https?:\/\//, '')
      .replace(/\/.*$/, '')
      .toLowerCase()

    const existing = await prisma.site.findFirst({
      where: { domain: cleanDomain, deleted_at: null },
    })
    if (existing) {
      return reply.code(409).send({ error: 'โดเมนนี้ถูกลงทะเบียนแล้ว' })
    }

    const site = await prisma.site.create({
      data: { name, domain: cleanDomain },
      select: {
        id: true,
        name: true,
        domain: true,
        tracking_token: true,
        created_at: true,
      },
    })

    logActivity({ userId: request.user.sub, userName: request.user.username, action: 'create', entityType: 'site', entityId: site.id, description: `สร้างเว็บไซต์ "${name}" (${cleanDomain})`, siteId: site.id })
    return reply.code(201).send(site)
  })

  // ── GET /api/sites ─────────────────────────────────────────────────────────

  app.get('/sites', async (request, reply) => {
    const accessibleIds = await getAccessibleSiteIds(request.user.sub, request.user.role)

    const sites = await prisma.site.findMany({
      where: {
        deleted_at: null,
        ...(accessibleIds !== null ? { id: { in: accessibleIds } } : {}),
      },
      select: {
        id: true,
        name: true,
        domain: true,
        tracking_token: true,
        created_at: true,
      },
      orderBy: { created_at: 'asc' },
    })

    return reply.send(sites)
  })

  // ── GET /api/sites/:id ─────────────────────────────────────────────────────

  app.get('/sites/:id', { schema: { params: idParamsSchema } }, async (request, reply) => {
    const site = await prisma.site.findFirst({
      where: { id: request.params.id, deleted_at: null },
      select: {
        id: true,
        name: true,
        domain: true,
        tracking_token: true,
        created_at: true,
      },
    })

    if (!site) return reply.code(404).send({ error: 'ไม่พบเว็บไซต์' })
    return reply.send(site)
  })

  // ── PUT /api/sites/:id ────────────────────────────────────────────────────

  const updateBodySchema = z.object({
    name: z.string().min(1).max(100).optional(),
    domain: z.string().min(1).max(253).optional(),
  })

  app.put('/sites/:id', { schema: { params: idParamsSchema, body: updateBodySchema }, preHandler: [requireRole('admin', 'developer')] }, async (request, reply) => {
    const site = await prisma.site.findFirst({
      where: { id: request.params.id, deleted_at: null },
    })
    if (!site) return reply.code(404).send({ error: 'ไม่พบเว็บไซต์' })

    const updated = await prisma.site.update({
      where: { id: request.params.id },
      data: {
        ...(request.body.name !== undefined && { name: request.body.name }),
        ...(request.body.domain !== undefined && { domain: request.body.domain }),
      },
    })

    logActivity({ userId: request.user.sub, userName: request.user.username, action: 'update', entityType: 'site', entityId: updated.id, description: `แก้ไขเว็บไซต์ "${updated.name}"`, siteId: updated.id, metadata: { name: request.body.name, domain: request.body.domain } })
    return reply.send(updated)
  })

  // ── DELETE /api/sites/:id ──────────────────────────────────────────────────

  app.delete('/sites/:id', { schema: { params: idParamsSchema }, preHandler: [requireRole('admin')] }, async (request, reply) => {
    const site = await prisma.site.findFirst({
      where: { id: request.params.id, deleted_at: null },
      select: { id: true },
    })

    if (!site) return reply.code(404).send({ error: 'ไม่พบเว็บไซต์' })

    const siteData = await prisma.site.findFirst({ where: { id: request.params.id }, select: { name: true, domain: true } })
    // Soft delete — event data is retained for historical analytics
    await prisma.site.update({
      where: { id: request.params.id },
      data: { deleted_at: new Date() },
    })

    logActivity({ userId: request.user.sub, userName: request.user.username, action: 'delete', entityType: 'site', entityId: request.params.id, description: `ลบเว็บไซต์ "${siteData?.name}" (${siteData?.domain})`, siteId: request.params.id })
    return reply.code(204).send()
  })
}
